name: tag-master
on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: fetch version Label                          
        run: |    
              echo The PR was merged
              git checkout master
              HEAD_VERSION=$( grep '$version = ' ZonPHP/inc/version_info.php | cut -d '"' -f 2  )
              echo "DIST_VERSION=${HEAD_VERSION}" >> $GITHUB_ENV
              
        - name: Create Tag
              uses: actions/github-script@v6
              with:
                script: |
                  const {DIST_VERSION} = process.env        
                  echo new label $DIST_VERSION
                  github.rest.git.createRef({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      ref: `refs/tags/${DIST_VERSION}`,
                      sha: context.sha
                  })      
    