on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/github-script@v6
    - run: |    
          git checkout master
          HEAD_VERSION=$( grep '$version = ' ZonPHP/inc/version_info.php | cut -d '"' -f 2  )
          echo "DIST_VERSION=${HEAD_VERSION}" >> $GITHUB_ENV
          git tag ${DIST_VERSION}
    - run: git push